file(STRINGS ${PROJECT_SOURCE_DIR}/cmd/text/main.txt BILLING_CMD_TEXT_HELP_MAIN NEWLINE_CONSUME)
string(REPLACE "\n" "\\n\"\n\"" BILLING_CMD_TEXT_HELP_MAIN ${BILLING_CMD_TEXT_HELP_MAIN})

file(STRINGS ${PROJECT_SOURCE_DIR}/cmd/text/up.txt BILLING_CMD_TEXT_HELP_UP NEWLINE_CONSUME)
string(REPLACE "\n" "\\n\"\n\"" BILLING_CMD_TEXT_HELP_UP ${BILLING_CMD_TEXT_HELP_UP})

file(STRINGS ${PROJECT_SOURCE_DIR}/cmd/text/stop.txt BILLING_CMD_TEXT_HELP_STOP NEWLINE_CONSUME)
string(REPLACE "\n" "\\n\"\n\"" BILLING_CMD_TEXT_HELP_STOP ${BILLING_CMD_TEXT_HELP_STOP})

file(STRINGS ${PROJECT_SOURCE_DIR}/cmd/text/show_users.txt BILLING_CMD_TEXT_HELP_SHOW_USERS NEWLINE_CONSUME)
string(REPLACE "\n" "\\n\"\n\"" BILLING_CMD_TEXT_HELP_SHOW_USERS ${BILLING_CMD_TEXT_HELP_SHOW_USERS})

file(STRINGS ${PROJECT_SOURCE_DIR}/cmd/text/version.txt BILLING_CMD_TEXT_HELP_VERSION NEWLINE_CONSUME)
string(REPLACE "\n" "\\n\"\n\"" BILLING_CMD_TEXT_HELP_VERSION ${BILLING_CMD_TEXT_HELP_VERSION})

# configure
configure_file(${PROJECT_SOURCE_DIR}/cmd/help_text.h.in ${PROJECT_SOURCE_DIR}/cmd/help_text.h)