name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build
        run: |
          ./build.sh
          cd cmake-build-billing
          mkdir -p billing-release-static
          cp billing config.yaml ./billing-release-static/
          tar -zcf billing-release-static.tar.gz billing-release-static
          rm ./*.txt
          cd ..
          ./build.sh shared
          cd cmake-build-billing
          mkdir -p billing-release-shared
          cp -r billing config.yaml lib ./billing-release-shared/
          tar -zcf billing-release-shared.tar.gz billing-release-shared
          ls -alh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
         files: cmake-build-billing/billing-release-*.tar.gz
         draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
